package dev.jasmeetsingh.firebaseauth

import android.app.Activity
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

actual class FirebaseAuth actual constructor() {

    private val auth = FirebaseAuth.getInstance()

    actual fun currentUser(): Flow<AuthUser?> = callbackFlow {
        val listener = com.google.firebase.auth.FirebaseAuth.AuthStateListener { firebaseAuth ->
            trySend(firebaseAuth.currentUser?.toAuthUser())
        }
        auth.addAuthStateListener(listener)
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    actual suspend fun signUpWithEmail(email: String, password: String): AuthUser {
        val result = auth.createUserWithEmailAndPassword(email, password).await()
        return result.user?.toAuthUser() ?: error("No user returned after sign up")
    }

    actual suspend fun signInWithEmail(email: String, password: String): AuthUser {
        val result = auth.signInWithEmailAndPassword(email, password).await()
        return result.user?.toAuthUser() ?: error("No user returned after sign in")
    }

    actual suspend fun signInWithGoogle(): AuthUser {
        val activity = ActivityProvider.activity
            ?: error("Activity not set. Call ActivityProvider.activity = this from your MainActivity.")

        val webClientId = ActivityProvider.webClientId
            ?: error("Web Client ID not set. Enable Google Sign-In in Firebase Console and update google-services.json.")

        val credentialManager = CredentialManager.create(activity)

        val googleIdOption = GetSignInWithGoogleOption.Builder(webClientId).build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val credentialResponse = credentialManager.getCredential(activity, request)
        val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credentialResponse.credential.data)

        val firebaseCredential = GoogleAuthProvider.getCredential(googleIdTokenCredential.idToken, null)
        val authResult = auth.signInWithCredential(firebaseCredential).await()

        return authResult.user?.toAuthUser() ?: error("No user returned after Google sign in")
    }

    actual suspend fun signOut() {
        auth.signOut()
    }

    actual suspend fun sendPasswordResetEmail(email: String) {
        auth.sendPasswordResetEmail(email).await()
    }

    private fun FirebaseUser.toAuthUser() = AuthUser(
        uid = uid,
        email = email,
        displayName = displayName,
        isEmailVerified = isEmailVerified
    )
}

object ActivityProvider {
    var activity: Activity? = null

    // Auto-generated by google-services plugin from google-services.json
    // after enabling Google Sign-In in Firebase Console.
    // Uses R.string.default_web_client_id at runtime.
    var webClientId: String? = null
}
