package dev.jasmeetsingh.firebaseauth

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge

class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        enableEdgeToEdge()
        super.onCreate(savedInstanceState)

        ActivityProvider.activity = this
        // default_web_client_id is auto-generated by google-services plugin
        // from google-services.json after enabling Google Sign-In in Firebase Console.
        val resId = resources.getIdentifier("default_web_client_id", "string", packageName)
        if (resId != 0) {
            ActivityProvider.webClientId = getString(resId)
        }

        setContent {
            App()
        }
    }

    override fun onDestroy() {
        ActivityProvider.activity = null
        super.onDestroy()
    }
}
